import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { parse } from "yaml";
const root = new URL("../", import.meta.url);
const env = { ...process.env };
for (const name of ["DEVELOPER_ID", "NOTARY_KEY", "NOTARY_KEY_ID", "NOTARY_ISSUER", "APP_VERSION"]) delete env[name];
const result = spawnSync("scripts/sign-and-package.sh", [], { cwd: root, env, encoding: "utf8" });
assert.equal(result.status, 1);
assert.match(result.stderr, /Required release credential\/value missing: DEVELOPER_ID/);
const release = parse(readFileSync(new URL(".github/workflows/release-app.yml", root), "utf8"));
assert.deepEqual(release.on.push.tags, ["v*"]);
assert.equal(release.jobs.release.needs, "verify");
const script = readFileSync(new URL("scripts/sign-and-package.sh", root), "utf8");
assert.doesNotMatch(script, /--deep/);
assert.ok(script.indexOf('stapler validate') < script.indexOf('shasum -a 256'));
const entitlement = readFileSync(new URL("packaging/Fieldnotes.entitlements", root), "utf8");
assert.doesNotMatch(entitlement, /get-task-allow|disable-library-validation|allow-jit|allow-unsigned-executable-memory/);
console.log("Release fail-closed and artifact-order checks passed");
